Build with full LTO and enable process isolated sandboxed iframes
GrapheneOS/Vanadium pull request #176
Opened 2022-05-08 01:23 UTC by Zanthed

2022-05-19 14:45 UTC, flawedworld requested changes

2022-05-19 14:45 UTC, flawedworld commented on patches/0084-build-with-full-LTO.patch
> +-    cflags += [ "-flto=thin" ]
We should add a gn arg to build with full LTO instead of doing this, because it will just be annoying when doing dev.

2022-05-19 16:09 UTC, Zanthed commented
I'll figure out if I can make it a gn arg. The issue is I need to set ldflags and cflags which are already nested in other if statements.

2022-06-15 17:01 UTC, Zanthed commented
Can't figure out making full LTO an args.gn flag.

Just cherry pick the other patch and port it to latest Chromium.

2022-06-15 17:01 UTC, closed without merging